<?php

if (isset($_POST['emailAddress']) && isset($_POST['emailBody'])){

    $emailDraft = $_POST['emailBody'];
    $emailAddress = $_POST['emailAddress'];


    $signature = "This message was automatically generated by Paratransit Pal.";

    $to = "oddlyaromatic@gmail.com";
    $from = "pmpincmn@bellsouth.net";
    $subject =  "Incident report";

    $message = urldecode($emailDraft) . $signature;

    $headers  = 'MIME-Version: 1.0' . "\r\n";
    $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
    $headers .= "From:" . $from . "\r\n";

    mail($to,$subject,$message,$headers);
}
